<!doctypehtml>
<!-- =========================================================
* Developed by Darth Vader
==============================================================

 IOT Platform - MQTT/HTTP
 Author: Darth Vader
 Version: 1.2.0

=========================================================
 -->
<html dir=rtl lang=fa><meta charset=utf-8><title>زیباسازی شهرداری تهران</title><meta content="width=device-width,initial-scale=1"name=viewport><meta content="DMG-IoT"name=description><meta content=Darth-Vader name=author><link href=<?=base_url()?>assets/images/favicon.ico rel="shortcut icon"><link href=<?=base_url()?>assets/libs/sweetalert2/sweetalert2.min.css rel=stylesheet><link href=<?=base_url()?>assets/css/bootstrap.min.css rel=stylesheet id=bootstrap-style><link href=<?=base_url()?>assets/css/icons.css rel=stylesheet><link href=<?=base_url()?>assets/css/app.css rel=stylesheet id=app-style><meta content=#283D92 name=theme-color><div class="account-pages my-5 pt-sm-5"><div class=container><div class="justify-content-center row"><div class="col-lg-6 col-md-8 col-xl-5"><div class="card overflow-hidden"><div class="text-center bg-login"><div class=bg-login-overlay></div><div class=position-relative><h5 class="font-size-20 text-white">پنل مدیریت پلتفرم IOT شهرداری تهران</h5><p class="mb-0 text-white-50">نام کاربری و رمز ورود را وارد کنید</p><a class="mt-4 logo logo-admin"href=index.html><img alt=""height=50 src=<?=base_url()?>assets/images/logo-sm-dark.png></a></div></div><div class="card-body pt-5"><div class=p-2><form autocomplete=on class=form-horizontal onsubmit=return!1><div class=form-group><label for=username>نام کاربری</label> <input id=userName class=form-control placeholder="نام کاربری را وارد کنید"></div><div class=form-group><label for=userpassword>رمز عبور</label> <input id=Password class=form-control placeholder="رمز عبور را وارد کنید"type=password></div><input id=remember_pwd type=checkbox> <label>به خاطر سپاری</label><div class=mt-3><button class="btn btn-block btn-primary waves-effect waves-light" id=loginForm onclick="login()" type=submit>ورود</button></div><div class="mt-4 text-center"><a class=text-muted href=pages-recoverpw.html><i class="mdi mdi-lock mr-1"></i> رمز عبور خود را فراموش کرده اید؟</a></div></form></div></div></div></div></div></div></div><script src=<?=base_url()?>assets/libs/jquery/jquery.min.js></script><script src=<?=base_url()?>assets/libs/bootstrap/js/bootstrap.bundle.min.js></script><script src=<?=base_url()?>assets/libs/metismenu/metisMenu.min.js></script><script src=<?=base_url()?>assets/libs/simplebar/simplebar.min.js></script><script src=<?=base_url()?>assets/libs/node-waves/waves.min.js></script><script src=<?=base_url()?>assets/libs/sweetalert2/sweetalert2.min.js></script><script src=<?=base_url()?>assets/js/pages/sweet-alerts.init.js></script><script src=<?=base_url()?>assets/js/app.js></script><script src=<?=base_url()?>assets/js/main.js></script>